# Exploring

## Imports

In [3]:
import pandas as pd





df = pd.read_stata("../data/HCMST Couples Meet 2017-2022 v2.2.dta", convert_categoricals=True)

/var/folders/lk/bg_vtzyj3fz74y0bzpbl63fm0000gn/T/ipykernel_80218/3423192363.py:7: UnicodeWarning:
One or more strings in the dta file could not be decoded using utf-8, and
so the fallback encoding of latin-1 is being used.  This can happen when a file
has been incorrectly encoded by Stata or some other software. You should verify
the string values returned are correct.
  df = pd.read_stata("../data/HCMST Couples Meet 2017-2022 v2.2.dta", convert_categoricals=True)

## Getting an idea of the data

- 3.510 rows
- 725 columns. wow.
- data types : category(586), datetime64[s](8), float32(46), float64(81), int16(1), int32(1), int8(2)

In [4]:
# Data size and shape

df.info()
#df.describe()
df_types = df.dtypes
df_types.info()
#df_types.groupby("value")
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3510 entries, 0 to 3509
Columns: 725 entries, caseid_new to p20_ppp2date2020
dtypes: category(586), datetime64[ns](8), float32(46), float64(81), int16(1), int32(1), int8(2)
memory usage: 5.1 MB
<class 'pandas.core.series.Series'>
Index: 725 entries, caseid_new to p20_ppp2date2020
Series name: None
Non-Null Count  Dtype
--------------  -----
725 non-null    object
dtypes: object(1)
memory usage: 27.5+ KB

,caseid_new,w3_Weight,w3_Weight_LGB,w3_combo_weight,w3_attrition_adj_weight,w2_weight_genpop,w2_weight_LGB,w2_combo_weight,w2_attrition_adj_weights,w1_weight_combo,...,p20_pppa1634,p20_pppa1902,p20_pppa1903,p20_pppa1904,p20_ppp22001,p20_pppa1905,p20_pppa1648,p20_ppp20072,p20_ppp20071,p20_ppp2date2020
0,53001,0.4422,NaN,0.495308,0.400185,0.3856,NaN,0.437670,0.380351,0.426861,...,Female,No,Female,No,No,No,No religion,Never,NaN,20210506.0
1,71609,0.8284,NaN,0.927891,0.879258,0.9196,NaN,1.043778,0.953948,1.295508,...,Female,No,Female,No,No,No,"Evangelical or Protestant Christian (Baptist, ...",Once a year or less,Yes,20201118.0
2,106983,0.8255,NaN,0.924643,0.706467,0.7748,NaN,0.879425,0.724682,1.126573,...,Male,Male,No,No,No,No,Catholic,A few times a year,No,20210429.0
3,121759,NaN,NaN,NaN,NaN,0.9177,NaN,1.041622,0.793093,0.933440,...,Male,Male,No,No,No,No,Other Christian religion,Once a week,Yes,20210507.0
4,158083,0.8810,NaN,0.986809,0.655467,0.8697,NaN,0.987140,0.735473,0.931291,...,Male,Male,No,No,No,No,No religion,Never,NaN,20210602.0

### Splitting the data set into waves

In [5]:
wave1_part = []
wave2_part = []
wave3_part = []
others_part = []
for column in df.columns:
    if column.startswith("w1") | column.startswith("p17"):
        wave1_part.append(column)
    elif column.startswith("w2")| column.startswith("p18")| column.startswith("p19")| column.startswith("p20"):
        wave2_part.append(column)
    elif column.startswith("w3"):
        wave3_part.append(column)
    else:
        others_part.append(column)

df_w1 = df[wave1_part+others_part]
df_w2 = df[wave2_part+others_part]
df_w3 = df[wave3_part+others_part]

In [ ]:
df_w2.columns.to_list()

In [22]:
df_w2["w2_relationship_end"].value_counts()

w2_relationship_end
no report of breakup or partner death    1879
Separation or other breakup               153
Partner died                               41
Divorce                                    34
Name: count, dtype: int64

In [23]:
df

,caseid_new,w3_Weight,w3_Weight_LGB,w3_combo_weight,w3_attrition_adj_weight,w2_weight_genpop,w2_weight_LGB,w2_combo_weight,w2_attrition_adj_weights,w1_weight_combo,...,p20_pppa1634,p20_pppa1902,p20_pppa1903,p20_pppa1904,p20_ppp22001,p20_pppa1905,p20_pppa1648,p20_ppp20072,p20_ppp20071,p20_ppp2date2020
0,53001,0.4422,NaN,0.495308,0.400185,0.3856,NaN,0.437670,0.380351,0.426861,...,Female,No,Female,No,No,No,No religion,Never,NaN,20210506.0
1,71609,0.8284,NaN,0.927891,0.879258,0.9196,NaN,1.043778,0.953948,1.295508,...,Female,No,Female,No,No,No,"Evangelical or Protestant Christian (Baptist, ...",Once a year or less,Yes,20201118.0
2,106983,0.8255,NaN,0.924643,0.706467,0.7748,NaN,0.879425,0.724682,1.126573,...,Male,Male,No,No,No,No,Catholic,A few times a year,No,20210429.0
3,121759,NaN,NaN,NaN,NaN,0.9177,NaN,1.041622,0.793093,0.933440,...,Male,Male,No,No,No,No,Other Christian religion,Once a week,Yes,20210507.0
4,158083,0.8810,NaN,0.986809,0.655467,0.8697,NaN,0.987140,0.735473,0.931291,...,Male,Male,No,No,No,No,No religion,Never,NaN,20210602.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3505,2967957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.594351,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3506,2968357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.196247,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3507,2968971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.383199,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3508,2969933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.197115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3509,2972135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.715531,...,Female,No,Female,No,No,No,Catholic,Once a week,No,20210308.0